# Generated by Django 3.0.5 on 2021-06-02 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 16, 23, 47, 753315)),
        ),
        migrations.AlterField(
            model_name='assessment_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 16, 23, 47, 753315)),
        ),
    ]
