# Generated by Django 3.0.5 on 2021-06-03 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210602_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 9, 30, 39, 933182)),
        ),
        migrations.AlterField(
            model_name='assessment_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 9, 30, 39, 933182)),
        ),
    ]
