# Generated by Django 3.0.5 on 2021-06-01 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Question',
            fields=[
                ('question_db_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Question_DB')),
                ('choice', models.CharField(default='E', max_length=3)),
                ('Client', models.ForeignKey(limit_choices_to={'groups__name': 'Client'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('questions.question_db',),
        ),
        migrations.CreateModel(
            name='ClientExam_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assessmentname', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('completed', models.IntegerField(default=0)),
                ('Client', models.ForeignKey(limit_choices_to={'groups__name': 'Client'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('qpaper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Question_Paper')),
                ('questions', models.ManyToManyField(to='Client.Client_Question')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=15)),
                ('DOB', models.CharField(blank=True, max_length=50)),
                ('BloodGroup', models.CharField(blank=True, max_length=50)),
                ('Height', models.CharField(blank=True, max_length=50)),
                ('Weight', models.CharField(blank=True, max_length=50)),
                ('waist', models.CharField(blank=True, max_length=50)),
                ('Heap', models.CharField(blank=True, max_length=50)),
                ('Diseases', models.CharField(blank=True, max_length=50)),
                ('Company', models.CharField(blank=True, max_length=50)),
                ('Designation', models.CharField(blank=True, max_length=50)),
                ('picture', models.ImageField(blank=True, upload_to='Client_profile_pics')),
            ],
            options={
                'verbose_name_plural': 'Client Info',
            },
        ),
        migrations.CreateModel(
            name='ClientResults_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assessment', models.ManyToManyField(to='Client.ClientExam_DB')),
                ('Client', models.ForeignKey(limit_choices_to={'groups__name': 'Client'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
