# Generated by Django 3.0.5 on 2021-06-01 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=15)),
                ('DOB', models.CharField(blank=True, max_length=50)),
                ('BloodGroup', models.CharField(blank=True, max_length=50)),
                ('Height', models.CharField(blank=True, max_length=50)),
                ('Weight', models.CharField(blank=True, max_length=50)),
                ('waist', models.CharField(blank=True, max_length=50)),
                ('heap', models.CharField(blank=True, max_length=50)),
                ('Diseases', models.CharField(blank=True, max_length=50)),
                ('Company', models.CharField(blank=True, max_length=50)),
                ('Designation', models.CharField(blank=True, max_length=50)),
                ('picture', models.ImageField(blank=True, upload_to='corporate_profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Corporate Info',
            },
        ),
    ]
