# Generated by Django 3.0.5 on 2021-06-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corporate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateinfo',
            name='Diseases',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
